### ISSUE TITLE
Feature Request - hooks for Block Pattern HTML elements

### ISSUE THREAD

**Issue by PavleMarjanovic** [godaddy-wordpress/go#839]
The user requested a [feature](https://wordpress.org/support/topic/req-feature-hooks-for-html-element/) that will enable hooks for block patter HTML elements within the theme.

For example, when they create or import a Block Pattern and use it as a footer, they intend to have it shown throughout the entire site not only on the page or section where they manually inserted it.

**Priority** (select one):
- [ ] High - Functional blocker
- [ ] Medium - Doesn't work as expected 
- [X] Low - Not a big deal but we'd want to get to this eventually

**Comment by jamabrey** [comment]
I would also like this but for the header.  Would like to add multiple images as logos that are responsive, instead of just one that scales down too much if we add them both into one image.

Here's the site that uses Go theme:
hospicefoundationok.org

Here's an example of what I'd like to do, that stacks on mobile using flex (it's one of our other sites that uses a different Wordpress theme):
keepmovingokc.org

**Comment by jrtashjian** [comment]
Closing this issue as it will be addressed in the [Full Site Editing](https://github.com/godaddy-wordpress/go/pull/855) work currently underway in Go.
